version: "3.8"

services:
  db:
    image: postgres:17
    container_name: vlab_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Cisco123
      POSTGRES_DB: vlab
    ports:
      - "5432:5432"
    volumes:
      - vlab_db_data:/var/lib/postgresql/data

volumes:
  vlab_db_data:
